### ISSUE TITLE
Does it support for batch estimation?

### ISSUE THREAD

**Issue by sukun1045** [FORTH-ModelBasedTracker/MonocularRGB_2D_Handjoints_MVA19#4]
It takes a while to feed image one by one. Can the network do estimation on a batch of hand images? Thank you.

**Comment by padeler** [comment]
Yes but you will have to adapt the pre process function to process multiple images. 

Check this [line](https://github.com/FORTH-ModelBasedTracker/MonocularRGB_2D_Handjoints_MVA19/blob/8bfea25d05260a0273c2841b0cc0e80621faef53/common/mva19.py#L82). The first dimension of the pre-procesed  image is the batch size.
